import mongoose from "mongoose";
import dotenv from "dotenv";
import bcrypt from "bcryptjs";
import User from "../models/Users.js";
import Publicite from "../models/Publicite.js";
import Thematique from "../models/Thematique.js";
import Categorie from "../models/Categorie.js";
import Produit from "../models/Produits.js";

dotenv.config();

const hashPassword = async (plainPassword) => {
  const salt = await bcrypt.genSalt(10);
  return bcrypt.hash(plainPassword, salt);
};

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ Connecté à MongoDB Atlas");

    // Vider les collections
    await Publicite.deleteMany();
    await Thematique.deleteMany();
    await Categorie.deleteMany();
    await Produit.deleteMany();
    //await User.deleteMany();

    console.log("🗑️ Collections vidées");

    // Insérer thématiques
const thematiques = await Thematique.insertMany([
  { nom: "Immobilier", image: "/images/thematique/immobilier.jpg", nbrFoisRecherché: 120 },
  { nom: "Véhicules", image: "/images/thematique/vehicules.jpg", nbrFoisRecherché: 95 },
  { nom: "Multimédia", image:"/images/thematique/multimédia.jpg" , nbrFoisRecherché: 80 },
  { nom: "Maison", image:"/images/thematique/maison.jpg", nbrFoisRecherché: 60 },
  { nom: "Loisirs", image:"/images/thematique/loisirs.jpg", nbrFoisRecherché: 45 },
  { nom: "Mode", image:"/images/thematique/mode.jpg", nbrFoisRecherché: 70 },
  { nom: "Électroménager", image:"/images/thematique/electromenager.jpg", nbrFoisRecherché: 55 },
  { nom: "Services", image:"/images/thematique/services.jpg", nbrFoisRecherché: 30 },
  { nom: "Animaux", image:"/images/thematique/animaux.jpg", nbrFoisRecherché: 20 },
  { nom: "Agriculture", image:"/images/thematique/agriculture.jpg", nbrFoisRecherché: 15 },
  { nom: "Industrie", image:"/images/thematique/industrie.jpg", nbrFoisRecherché: 10 },
  { nom: "Musique", image:"/images/thematique/musique.jpg", nbrFoisRecherché: 50 },
  { nom: "Sport", image:"/images/thematique/sport.jpg", nbrFoisRecherché: 40 },
  { nom: "Outillage", image:"/images/thematique/outillage.jpg", nbrFoisRecherché: 28 },
  { nom: "Sécurité", image:"/images/thematique/securite.jpg", nbrFoisRecherché: 5 },
]);

console.log("✅ Thématiques insérées");

// Insérer catégories
const categories = await Categorie.insertMany([
  // Immobilier
  { nom: "Appartements", image: "/images/categories/appartements.jpg", id_thematique: thematiques[0]._id },
  { nom: "Maisons", image: "/images/categories/maisons.jpg", id_thematique: thematiques[0]._id },
  { nom: "Terrains", image: "/images/categories/terrains.jpg", id_thematique: thematiques[0]._id },

  // Véhicules
  { nom: "Voitures", image: "/images/categories/voitures.jpg", id_thematique: thematiques[1]._id },
  { nom: "Motos", image: "/images/categories/motos.jpg", id_thematique: thematiques[1]._id },
  { nom: "Vélos", image: "/images/categories/velos.jpg", id_thematique: thematiques[1]._id },

  // Multimédia
  { nom: "Informatique", image: "/images/categories/informatique.jpg", id_thematique: thematiques[2]._id },
  { nom: "Téléphonie", image: "/images/categories/telephonie.jpg", id_thematique: thematiques[2]._id },
  { nom: "Gaming", image: "/images/categories/gaming.jpg", id_thematique: thematiques[2]._id },
  { nom: "Photo & Vidéo", image: "/images/categories/photo-video.jpg", id_thematique: thematiques[2]._id },

  // Maison
  { nom: "Meubles", image: "/images/categories/meubles.jpg", id_thematique: thematiques[3]._id },
  { nom: "Décoration", image: "/images/categories/decoration.jpg", id_thematique: thematiques[3]._id },
  { nom: "Jardinage", image: "/images/categories/jardinage.jpg", id_thematique: thematiques[3]._id },

  // Loisirs
  { nom: "Sport", image: "/images/categories/sport.jpg", id_thematique: thematiques[4]._id },
  { nom: "Musique", image: "/images/categories/musique.jpg", id_thematique: thematiques[4]._id },
  { nom: "Livres", image: "/images/categories/livres.jpg", id_thematique: thematiques[4]._id },

  // Mode
  { nom: "Vêtements", image: "/images/categories/vetements.jpg", id_thematique: thematiques[5]._id },
  { nom: "Chaussures", image: "/images/categories/chaussures.jpg", id_thematique: thematiques[5]._id },
  { nom: "Accessoires", image: "/images/categories/accessoires.jpg", id_thematique: thematiques[5]._id },

  // Électroménager
  { nom: "Cuisine", image: "/images/categories/cuisine.jpg", id_thematique: thematiques[6]._id },
  { nom: "Lavage", image: "/images/categories/lavage.jpg", id_thematique: thematiques[6]._id },
  { nom: "Climatisation", image: "/images/categories/climatisation.jpg", id_thematique: thematiques[6]._id },

  // Services
  { nom: "Cours particuliers", image: "/images/categories/cours-particuliers.jpg", id_thematique: thematiques[7]._id },
  { nom: "Dépannage", image: "/images/categories/depannage.jpg", id_thematique: thematiques[7]._id },
  { nom: "Événementiel", image: "/images/categories/evenementiel.jpg", id_thematique: thematiques[7]._id },

  // Animaux
  { nom: "Chiens", image: "/images/categories/chiens.jpg", id_thematique: thematiques[8]._id },
  { nom: "Chats", image: "/images/categories/chats.jpg", id_thematique: thematiques[8]._id },
  { nom: "Accessoires animaux", image: "/images/categories/accessoires-animaux.jpg", id_thematique: thematiques[8]._id },

  // Agriculture
  { nom: "Matériel agricole", image: "/images/categories/materiel-agricole.jpg", id_thematique: thematiques[9]._id },
  { nom: "Animaux de ferme", image: "/images/categories/animaux-ferme.jpg", id_thematique: thematiques[9]._id },
  { nom: "Produits agricoles", image: "/images/categories/produits-agricoles.jpg", id_thematique: thematiques[9]._id },
  { nom: "Vêtements agricoles", image: "/images/categories/vetements-agricoles.jpg", id_thematique: thematiques[9]._id },
  { nom: "Jardinage", image: "/images/categories/jardinage-agricole.jpg", id_thematique: thematiques[9]._id },
  
  // Industrie
  { nom: "Matériel industriel", image: "/images/categories/materiel-industriel.jpg", id_thematique: thematiques[10]._id },
  { nom: "Fournitures industrielles", image: "/images/categories/fournitures-industrielles.jpg", id_thematique: thematiques[10]._id },
  { nom: "Vêtements de travail", image: "/images/categories/vetements-travail.jpg", id_thematique: thematiques[10]._id },
  { nom: "Sécurité", image: "/images/categories/securite.jpg", id_thematique: thematiques[10]._id },

  // Musique
  { nom: "Instruments de musique", image: "/images/categories/instruments-musique.jpg", id_thematique: thematiques[11]._id },
  { nom: "Équipement audio", image: "/images/categories/equipement-audio.jpg", id_thematique: thematiques[11]._id },
  { nom: "Partitions", image: "/images/categories/partitions.jpg", id_thematique: thematiques[11]._id },
  { nom: "Accessoires musique", image: "/images/categories/accessoires-musique.jpg", id_thematique: thematiques[11]._id },
  { nom: "appareils DJ", image: "/images/categories/appareils-dj.jpg", id_thematique: thematiques[11]._id },

  // Sport
  { nom: "Équipement sportif", image: "/images/categories/equipement-sportif.jpg", id_thematique: thematiques[12]._id },
  { nom: "Vêtements de sport", image: "/images/categories/vetements-sport.jpg", id_thematique: thematiques[12]._id },
  { nom: "Chaussures de sport", image: "/images/categories/chaussures-sport.jpg", id_thematique: thematiques[12]._id },
  { nom: "Accessoires sport", image: "/images/categories/accessoires-sport.jpg", id_thematique: thematiques[12]._id },

  // Outillage
  { nom: "Outils manuels", image: "/images/categories/outils-manuels.jpg", id_thematique: thematiques[13]._id },
  { nom: "Outils électriques", image: "/images/categories/outils-electriques.jpg", id_thematique: thematiques[13]._id },
  { nom: "Équipement de sécurité", image: "/images/categories/equipement-securite-outillage.jpg", id_thematique: thematiques[13]._id },
  { nom: "Accessoires outillage", image: "/images/categories/accessoires-outillage.jpg", id_thematique: thematiques[13]._id },
]);

console.log("✅ Catégories insérées");


    // Insérer produits
const produits = await Produit.insertMany([
  {
    titre: "MacBook Pro 2022",
    description: "Ordinateur portable puissant pour développeurs",
    prix: 1800,
    location: "Paris",
    state: "occasion",
    sellerType: "professionnel",
    images: ["/images/produits/macbook.jpg"], // tableau d'images
    id_categorie: categories.find(cat => cat.nom === "Informatique")._id,
    theme: thematiques.find(t => t.nom === "Multimédia").nom,
    vues: 120,
    date: new Date("2023-11-01"),
  },
  {
    titre: "Voiture Peugeot 208",
    description: "Bonne occasion, faible kilométrage",
    prix: 9500,
    location: "Lyon",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/peugeot208.jpg"], // tableau d'images
    id_categorie: categories.find(cat => cat.nom === "Voitures")._id,
    theme: thematiques.find(t => t.nom === "Véhicules").nom,
    vues: 300,
    date: new Date("2023-10-25"),
  },
  {
    titre: "Canapé 3 places",
    description: "Confortable et moderne, parfait pour salon",
    prix: 300,
    location: "Marseille",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/canape.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Meubles")._id,
    theme: thematiques.find(t => t.nom === "Immobilier").nom,
    vues: 85,
    date: new Date("2023-10-20"),
  },
  {
    titre: "iPhone 14 Pro Max",
    description: "Smartphone Apple dernière génération, état impeccable",
    prix: 1200,
    location: "Bordeaux",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/iphone14.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Téléphonie")._id,
    theme: thematiques.find(t => t.nom === "Multimédia").nom,
    vues: 450,
    date: new Date("2023-11-05"),
  },
  {
    titre: "Vélo électrique Decathlon",
    description: "Idéal pour trajets urbains, autonomie 80km",
    prix: 800,
    location: "Toulouse",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/velo.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Vélos")._id,
    theme: thematiques.find(t => t.nom === "Véhicules").nom,
    vues: 210,
    date: new Date("2023-09-18"),
  },
  {
    titre: "Table en bois massif",
    description: "Table à manger 6 personnes, style moderne",
    prix: 450,
    location: "Nice",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/table.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Meubles")._id,
    theme: thematiques.find(t => t.nom === "Maison").nom,
    vues: 60,
    date: new Date("2023-09-10"),
  },
  {
    titre: "PS5 + 2 manettes",
    description: "Console Sony PlayStation 5 avec 2 manettes et 3 jeux",
    prix: 650,
    location: "Paris",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/ps5.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Gaming")._id,
    theme: thematiques.find(t => t.nom === "Multimédia").nom,
    vues: 780,
    date: new Date("2023-11-08"),
  },
  {
    titre: "Appareil photo Canon EOS R",
    description: "Appareil photo hybride professionnel avec objectif 24-105mm",
    prix: 2100,
    location: "Lille",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/canon.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Photo & Vidéo")._id,
    theme: thematiques.find(t => t.nom === "Multimédia").nom,
    vues: 150,
    date: new Date("2023-08-22"),
  },
  {
    titre: "Chaussures Nike Air Max",
    description: "Sneakers tendance, taille 42, état neuf",
    prix: 120,
    location: "Strasbourg",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/nike.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Chaussures")._id,
    theme: thematiques.find(t => t.nom === "Mode").nom,
    vues: 95,
    date: new Date("2023-11-03"),
  },
  {
    titre: "Livre : L’art de la guerre",
    description: "Édition reliée, excellent état",
    prix: 15,
    location: "Rennes",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/livre.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Livres")._id,
    theme: thematiques.find(t => t.nom === "Loisirs").nom,
    vues: 40,
    date: new Date("2023-07-30"),
  },
  {   titre: "Machine à laver Samsung",
    description: "Machine à laver 8kg, très bon état",
    prix: 300,
    location: "Nantes",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/lave-linge.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Lavage")._id,
    theme: thematiques.find(t => t.nom === "Électroménager").nom,
    vues: 75,
    date: new Date("2023-10-15"),
  },
  {
    titre: "Guitare acoustique Yamaha",
    description: "Guitare pour débutants, son clair et agréable",
    prix: 150,
    location: "Montpellier",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/guitare.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Instruments de musique")._id,
    theme: thematiques.find(t => t.nom === "Musique").nom,
    vues: 110,
    date: new Date("2023-09-05"),
  },
  {    titre: "Tondeuse à gazon électrique",
    description: "Tondeuse légère, idéale pour petits jardins",
    prix: 200,
    location: "Dijon",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/tondeuse.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Jardinage")._id,
    theme: thematiques.find(t => t.nom === "Maison").nom,
    vues: 55,
    date: new Date("2023-08-12"),
  },
  {    titre: "Montre connectée Fitbit",
    description: "Suivi d’activité, fréquence cardiaque, GPS intégré",
    prix: 130,
    location: "Angers",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/fitbit.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Accessoires")._id,
    theme: thematiques.find(t => t.nom === "Mode").nom,
    vues: 200,
    date: new Date("2023-11-06"),
  },
  {    titre: "Casque audio Bose",
    description: "Casque à réduction de bruit, son immersif",
    prix: 250,
    location: "Grenoble",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/bose.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Équipement audio")._id,
    theme: thematiques.find(t => t.nom === "Musique").nom,
    vues: 180,
    date: new Date("2023-10-28"),
  },
  {    titre: "Tapis de yoga antidérapant",
    description: "Tapis épais et confortable, idéal pour le yoga et le pilates",
    prix: 40,
    location: "Tours",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/tapis-yoga.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Équipement sportif")._id,
    theme: thematiques.find(t => t.nom === "Sport").nom,
    vues: 90,
    date: new Date("2023-09-22"),
  },
  {    titre: "Perceuse sans fil Bosch",
    description: "Perceuse 18V avec batterie et chargeur, idéale pour bricolage",
    prix: 120,
    location: "Le Havre",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/perceuse.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Outils électriques")._id,
    theme: thematiques.find(t => t.nom === "Outillage").nom,
    vues: 65,
    date: new Date("2023-10-10"),
  },
  {    titre: "Accessoires pour animaux",
    description: "Lot de jouets et accessoires pour chiens et chats",
    prix: 35,
    location: "Nîmes",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/accessoires-animaux.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Accessoires animaux")._id,
    theme: thematiques.find(t => t.nom === "Animaux").nom,
    vues: 40,
    date: new Date("2023-08-30"),
  },
  {    titre: "Tracteur agricole John Deere",
    description: "Tracteur 4 roues motrices, parfait pour travaux agricoles",
    prix: 15000,
    location: "Clermont-Ferrand",
    state: "occasion",
    sellerType: "professionnel",
    images: ["/images/produits/tracteur.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Matériel agricole")._id,
    theme: thematiques.find(t => t.nom === "Agriculture").nom,
    vues: 25,
    date: new Date("2023-07-15"),
  },
  {    titre: "Équipement de sécurité industriel",
    description: "Casques, gants et lunettes de protection pour chantier",
    prix: 300,
    location: "Le Mans",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/equipement-securite.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Équipement de sécurité")._id,
    theme: thematiques.find(t => t.nom === "Industrie").nom,
    vues: 15,
    date: new Date("2023-09-12"),
  },
  {   titre: "peugeot 3008",
    description: "SUV familial, faible kilométrage, très bon état",
    prix: 22000,
    location: "Paris",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/peugeot3008.jpg"], // tableau d'images
    id_categorie: categories.find(cat => cat.nom === "Voitures")._id,
    theme: thematiques.find(t => t.nom === "Véhicules").nom,
    vues: 180,
    date: new Date("2023-10-30"),
  },
  {    titre: "Appartement T2 à Lyon",
    description: "Appartement 2 pièces, 45m², proche transports et commerces",
    prix: 850,
    location: "Lyon",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/appartement.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Appartements")._id,
    theme: thematiques.find(t => t.nom === "Immobilier").nom,
    vues: 95,
    date: new Date("2023-11-02"),
  }, 
  {    titre: "Samsung Galaxy S23 Ultra",
    description: "Smartphone Android haut de gamme, écran 6.8\", 256GB",
    prix: 1150,
    location: "Bordeaux",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/galaxy-s23.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Téléphonie")._id,
    theme: thematiques.find(t => t.nom === "Multimédia").nom,
    vues: 320,
    date: new Date("2023-11-07"),
  },
  {    titre: "Vélo de route Cannondale",
    description: "Vélo léger en carbone, parfait pour la compétition",
    prix: 900,
    location: "Toulouse",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/cannondale.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Vélos")._id,
    theme: thematiques.find(t => t.nom === "Véhicules").nom,
    vues: 140,
    date: new Date("2023-10-18"),
  },
  {    titre: "Enceinte Bluetooth JBL",
    description: "Enceinte portable avec son puissant et étanche",
    prix: 80,
    location: "Lille",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/jbl.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Équipement audio")._id,
    theme: thematiques.find(t => t.nom === "Musique").nom,
    vues: 220,
    date: new Date("2023-10-29"),
  },
  {    titre: "Veste en cuir homme",
    description: "Veste en cuir véritable, taille M, style biker",
    prix: 200,
    location: "Strasbourg",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/veste-cuir.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Vêtements")._id,
    theme: thematiques.find(t => t.nom === "Mode").nom,
    vues: 75,
    date: new Date("2023-09-25"),
  },
  {    titre: "Montre Seiko automatique",
    description: "Montre de luxe avec mouvement automatique, état neuf",
    prix: 350,
    location: "Rennes",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/montre-seiko.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Accessoires")._id,
    theme: thematiques.find(t => t.nom === "Mode").nom,
    vues: 60,
    date: new Date("2023-10-05"),
  }, 
  {    titre: "Tablette iPad Air",
    description: "Tablette Apple iPad Air 10.9\", 64GB, Wi-Fi",
    prix: 600,
    location: "Nantes",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/ipad-air.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Informatique")._id,
    theme: thematiques.find(t => t.nom === "Multimédia").nom,
    vues: 280,
    date: new Date("2023-11-04"),
  }, 
  {    titre: "Chaise de bureau ergonomique",
    description: "Chaise avec support lombaire, réglable en hauteur",
    prix: 150,
    location: "Montpellier",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/chaise-bureau.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Meubles")._id,
    theme: thematiques.find(t => t.nom === "Maison").nom,
    vues: 45,
    date: new Date("2023-09-15"),
  },
  {    titre: "Xbox Series X",
    description: "Console de jeu dernière génération avec 1TB de stockage",
    prix: 500,
    location: "Dijon",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/xbox.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Gaming")._id,
    theme: thematiques.find(t => t.nom === "Multimédia").nom,
    vues: 400,
    date: new Date("2023-10-27"),
  },
  {    titre: "Drone DJI Mini 2",
    description: "Drone compact avec caméra 4K, idéal pour débutants",
    prix: 450,
    location: "Le Havre",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/drone.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Photo & Vidéo")._id,
    theme: thematiques.find(t => t.nom === "Multimédia").nom,
    vues: 130,
    date: new Date("2023-10-12"),
  },
  {    titre: "Robe de soirée",
    description: "Robe élégante taille S, parfaite pour événements",
    prix: 80,
    location: "Nîmes",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/robe-soiree.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Vêtements")._id,
    theme: thematiques.find(t => t.nom === "Mode").nom,
    vues: 55,
    date: new Date("2023-09-28"),
  },
  {    titre: "Climatiseur mobile",
    description: "Climatiseur 12000 BTU, idéal pour pièces jusqu’à 35m²",
    prix: 350,
    location: "Clermont-Ferrand",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/climatiseur.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Climatisation")._id,
    theme: thematiques.find(t => t.nom === "Électroménager").nom,
    vues: 70,
    date: new Date("2023-10-08"),
  },
  {    titre: "Accessoires de jardinage",
    description: "Lot d’outils de jardinage pour amateurs et professionnels",
    prix: 60,
    location: "Le Mans",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/outils-jardinage.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Jardinage")._id,
    theme: thematiques.find(t => t.nom === "Maison").nom,
    vues: 35,
    date: new Date("2023-09-18"),
  },
  {    titre: "Accessoires DJ",
    description: "Mixeur, platines et casque pour DJ professionnels",
    prix: 800,
    location: "Angers",
    state: "occasion",
    sellerType: "professionnel",
    images: ["/images/produits/accessoires-dj.jpg"],
    id_categorie: categories.find(cat => cat.nom === "appareils DJ")._id,
    theme: thematiques.find(t => t.nom === "Musique").nom,
    vues: 20,
    date: new Date("2023-08-25"),
  },
  {    titre: "Ballon de football Adidas",
    description: "Ballon officiel de la Ligue des Champions, taille 5",
    prix: 30,
    location: "Tours",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/ballon-foot.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Accessoires sport")._id,
    theme: thematiques.find(t => t.nom === "Sport").nom,
    vues: 85,
    date: new Date("2023-09-20"),
  },
  {  titre: "Coffret d’outils manuels",
    description: "Coffret complet avec tournevis, clés et marteau",
    prix: 70,
    location: "Le Havre",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/coffret-outils.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Outils manuels")._id,
    theme: thematiques.find(t => t.nom === "Outillage").nom,
    vues: 50,
    date: new Date("2023-10-14"),
  },
  {   titre: "Tesla Model 3",
    description: "Voiture électrique, autonomie 400km, état neuf",
    prix: 35000,
    location: "Paris",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/tesla.jpg"], // tableau d'images
    id_categorie: categories.find(cat => cat.nom === "Voitures")._id,
    theme: thematiques.find(t => t.nom === "Véhicules").nom,
    vues: 220,
    date: new Date("2023-11-09"),
  },
  {    titre: "Maison T4 à Marseille",
    description: "Maison 4 pièces, 120m², jardin et garage",
    prix: 250000,
    location: "Marseille",
    state: "occasion",
    sellerType: "professionnel",
    images: ["/images/produits/maison.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Maisons")._id,
    theme: thematiques.find(t => t.nom === "Immobilier").nom,
    vues: 130,
    date: new Date("2023-10-22"),
  },
  {    titre: "Surface Laptop 4",
    description: "Ordinateur portable Microsoft, écran 13.5\", 256GB",
    prix: 1400,
    location: "Lyon",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/surface.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Informatique")._id,
    theme: thematiques.find(t => t.nom === "Multimédia").nom,
    vues: 160,
    date: new Date("2023-11-01"),
  }, 
  {    titre: "Vélo VTT Specialized",
    description: "Vélo tout-terrain, cadre en aluminium, 21 vitesses",
    prix: 750,
    location: "Toulouse",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/vtt.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Vélos")._id,
    theme: thematiques.find(t => t.nom === "Véhicules").nom,
    vues: 110,
    date: new Date("2023-10-16"),
  },
  {    titre: "Casque VR Oculus Quest 2",
    description: "Casque de réalité virtuelle autonome avec contrôleurs",
    prix: 300,
    location: "Bordeaux",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/oculus.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Gaming")._id,
    theme: thematiques.find(t => t.nom === "Multimédia").nom,
    vues: 250,
    date: new Date("2023-10-30"),
  },
  {    titre: "Sac à dos Eastpak",
    description: "Sac à dos robuste, capacité 24L, idéal pour l’école ou le travail",
    prix: 60,
    location: "Lille",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/sac-dos.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Accessoires")._id,
    theme: thematiques.find(t => t.nom === "Mode").nom,
    vues: 80,
    date: new Date("2023-09-30"),
  },
  {    titre: "Objectif Canon 50mm f/1.8",
    description: "Objectif à focale fixe, idéal pour portraits et faible luminosité",
    prix: 120,
    location: "Strasbourg",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/objectif-canon.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Photo & Vidéo")._id,
    theme: thematiques.find(t => t.nom === "Multimédia").nom,
    vues: 140,
    date: new Date("2023-10-11"),
  },
  {    titre: "Short de sport Adidas",
    description: "Short léger et respirant, taille M",
    prix: 25,
    location: "Rennes",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/short-sport.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Vêtements de sport")._id,
    theme: thematiques.find(t => t.nom === "Sport").nom,
    vues: 70,
    date: new Date("2023-09-12"),
  },
  {    titre: "Scie circulaire Makita",
    description: "Scie puissante avec lame de 165mm, idéale pour le bois",
    prix: 180,
    location: "Nantes",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/scie-circulaire.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Outils électriques")._id,
    theme: thematiques.find(t => t.nom === "Outillage").nom,
    vues: 40,
    date: new Date("2023-10-05"),
  },
  {    titre: "Aquarium 100L",
    description: "Aquarium complet avec filtre, éclairage et décorations",
    prix: 150,
    location: "Nîmes",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/aquarium.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Accessoires animaux")._id,
    theme: thematiques.find(t => t.nom === "Animaux").nom,
    vues: 30,
    date: new Date("2023-08-28"),
  },
  {    titre: "Moissonneuse-batteuse Claas",
    description: "Moissonneuse-batteuse performante pour grandes exploitations",
    prix: 75000,
    location: "Clermont-Ferrand",
    state: "occasion",
    sellerType: "professionnel",
    images: ["/images/produits/moissonneuse.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Matériel agricole")._id,
    theme: thematiques.find(t => t.nom === "Agriculture").nom,
    vues: 10,
    date: new Date("2023-07-20"),
  },
  {    titre: "Gants de travail",
    description: "Gants résistants pour travaux lourds, taille L",
    prix: 15,
    location: "Le Mans",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/gants-travail.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Vêtements de travail")._id,
    theme: thematiques.find(t => t.nom === "Industrie").nom,
    vues: 20,
    date: new Date("2023-09-10"),
  },
  {    titre: "Détecteur de fumée",
    description: "Détecteur de fumée certifié NF, pile longue durée",
    prix: 25,
    location: "Angers",
    state: "neuf",
    sellerType: "particulier",
    images: ["/images/produits/detecteur-fumee.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Sécurité")._id,
    theme: thematiques.find(t => t.nom === "Sécurité").nom,
    vues: 15,
    date: new Date("2023-10-01"),
  },
  {    titre: "Piano numérique Yamaha",
    description: "Piano 88 touches avec pédales, idéal pour débutants et pros",
    prix: 600,
    location: "Tours",
    state: "occasion",
    sellerType: "particulier",
    images: ["/images/produits/piano.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Instruments de musique")._id,
    theme: thematiques.find(t => t.nom === "Musique").nom,
    vues: 90,
    date: new Date("2023-09-08"),
  },
  {    titre: "Tapis de course",
    description: "Tapis de course pliable avec plusieurs programmes d’entraînement",
    prix: 400,
    location: "Le Havre",
    state: "neuf",
    sellerType: "professionnel",
    images: ["/images/produits/tapis-course.jpg"],
    id_categorie: categories.find(cat => cat.nom === "Équipement sportif")._id,
    theme: thematiques.find(t => t.nom === "Sport").nom,
    vues: 60,
    date: new Date("2023-10-20"),
  },
]);

    console.log("✅ Produits insérés");

   // Insérer publicités
await Publicite.insertMany([
  {
    titre: "🔥 Promo Été",
    information: "Profitez de l'été pour équiper votre maison ! Jusqu'à -50% sur une sélection d'appareils électroménagers : réfrigérateurs, lave-linge, aspirateurs et plus encore. Offres limitées, ne manquez pas cette vague de réductions !",
    image: "/images/publicites/pub1.jpg"
  },
  {
    titre: "🚗 Nouveautés Auto",
    information: "Explorez l’avenir de la mobilité ! Découvrez les derniers modèles hybrides et 100% électriques, alliant performance, design et économies d’énergie. Essais gratuits et offres de lancement disponibles chez nos partenaires.",
    image: "/images/publicites/pub2.jpg"
  },
  {
    titre: "🏡 Offres Immo",
    information: "Envie de changer de vie ? Trouvez votre futur chez-vous parmi nos appartements et maisons à prix réduits partout en France. Opportunités exclusives, frais de notaire offerts sur certaines ventes !",
    image: "/images/publicites/pub3.jpg"
  },
  {
    titre: "💻 Tech Deals",
    information: "Cette semaine seulement : smartphones dernière génération, PC ultra-performants et gadgets connectés à prix cassés ! Stock limité, livraison express et garantie incluse. Faites le plein de technologie !",
    image: "/images/publicites/pub4.jpg"
  },
  {
    titre: "🛋️ Mobilier Design",
    information: "Transformez votre intérieur avec notre sélection de meubles modernes et élégants. Promotions exceptionnelles et livraison gratuite partout en France. Canapés, tables, rangements : style et confort à petit prix !",
    image: "/images/publicites/pub5.jpg"
  },
  {
    titre: "👗 Mode & Accessoires",
    information: "Soyez tendance avec nos nouvelles collections printemps-été ! Robes légères, sacs stylés, lunettes de soleil et bien plus. Offres exclusives en ligne et en boutique. L’élégance n’attend pas !",
    image: "/images/publicites/pub6.jpg"
  },
  {
    titre: "🏀 Sport & Loisirs",
    information: "Bougez sans vous ruiner ! Équipements sportifs, accessoires de fitness, vélos et jeux de plein air à prix mini. Idéal pour se remettre en forme ou s’amuser en famille. Promotions valables jusqu’à épuisement des stocks.",
    image: "/images/publicites/pub7.jpg"
  },
  {
    titre: "✈️ Voyages",
    information: "Envie d’évasion ? Réservez vos séjours et billets d’avion à prix réduit vers les plus belles destinations. Plages paradisiaques, escapades urbaines ou nature sauvage : partez sans vous ruiner !",
    image: "/images/publicites/pub8.jpg"
  },
]);
  console.log("✅ Publicités insérées");

    // Insérer utilisateurs
  //   const users = [
  //   {
  //     name: "Admin",
  //     firstname: "Admin",
  //     phonenumber: "0600000001",
  //     email: "admin@admin.com",
  //     password: await hashPassword("admin"), 
  //     role: "admin",
  //     adresse: {
  //       rue: "10 Rue de Rivoli",
  //       ville: "Paris",
  //       codePostal: "75001",
  //       pays: "France",
  //     },
  //   },
  //   {
  //     name: "Moderator",
  //     firstname: "Moderator",
  //     phonenumber: "0600000002",
  //     email: "moderator@Moderator.com",
  //     password: await hashPassword("moderator"),
  //     role: "moderator",
  //     adresse: {
  //       rue: "15 Avenue Foch",
  //       ville: "Lyon",
  //       codePostal: "69000",
  //       pays: "France",
  //     },
  //   },
  //   {
  //     name: "Martin",
  //     firstname: "Lucas",
  //     phonenumber: "0600000003",
  //     email: "user@test.com",
  //     password: await hashPassword("user123"),
  //     role: "user",
  //     adresse: {
  //       rue: "20 Rue de la République",
  //       ville: "Marseille",
  //       codePostal: "13000",
  //       pays: "France",
  //     },
  //   },
  // ];

  //await User.insertMany(users);

 // console.log("✅ Utilisateurs de test insérés avec succès !");

    console.log("🎉 Base de données initialisée avec succès !");
    process.exit();
  } catch (err) {
    console.error("❌ Erreur seed :", err);
    process.exit(1);
  }
};

seedDatabase();
